from typing import Any, Protocol


class MessageBoxAPI(Protocol):
    def showinfo(self, title: str, message: str, **options: Any) -> Any: ...
    def showerror(self, title: str, message: str, **options: Any) -> Any: ...
    def askyesno(self, title: str, message: str, **options: Any) -> bool: ...
